//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	public partial class Account
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Account()
		{
			this.Comments = new HashSet<Comment>();
			this.Histories = new HashSet<History>();
			this.LikedSongs = new HashSet<LikedSong>();
			this.PlayLists = new HashSet<PlayList>();
		}

		[Required(ErrorMessage = "This field is required")]
		[Display(Name = "Tên tài khoản")]
		public string TaiKhoan { get; set; }

		[Required(ErrorMessage = "This field is required")]
		[Display(Name = "Mật khẩu")]
		[DataType(DataType.Password)]
		public string MatKhau { get; set; }

		[Required(ErrorMessage = "This field is required")]
		[Display(Name = "Nhập lại mật khẩu")]
		[DataType(DataType.Password)]
		[Compare("MatKhau", ErrorMessage = "Confirm password doesn't match, type again!")]
		public string NhapLaiMatKhau { get; set; }

		[Required(ErrorMessage = "This field is required")]
		[Display(Name = "Biệt danh")]
		public string UserName { get; set; }

		[Display(Name = "Hình ảnh đại diện")]
		public string HinhAnh { get; set; }

		[Required(ErrorMessage = "This field is required")]
		[Display(Name = "Email")] // Tên hiển thị cho email
		[EmailAddress(ErrorMessage = "Invalid Email Address")] // Kiểm tra định dạng email
		public string Email { get; set; } // Thêm cột Email

		public int Role { get; set; }
		public int Ma_User { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Comment> Comments { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<History> Histories { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<LikedSong> LikedSongs { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<PlayList> PlayLists { get; set; }
	}
}
