//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cate_Song
    {
        public int ID_Cate_Song { get; set; }
        public int Ma_The_Loai { get; set; }
        public int Ma_Bai_Hat { get; set; }
    
        public virtual Song Song { get; set; }
        public virtual Category Category { get; set; }
    }
}
