//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Ma_Binh_Luan { get; set; }
        public int Ma_User { get; set; }
        public int Ma_Bai_Hat { get; set; }
        public int So_Sao { get; set; }
        public string Noi_Dung { get; set; }
        public System.DateTime Ngay_Binh_Luan { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Song Song { get; set; }
    }
}
