//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAPMMainEntities : DbContext
    {
        public DAPMMainEntities()
            : base("name=DAPMMainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Cate_Song> Cate_Song { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<LikedSong> LikedSongs { get; set; }
        public virtual DbSet<PlayList> PlayLists { get; set; }
        public virtual DbSet<Singer> Singers { get; set; }
        public virtual DbSet<Singer_Song> Singer_Song { get; set; }
        public virtual DbSet<Song_Play> Song_Play { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
        public virtual DbSet<Songs_Liked> Songs_Liked { get; set; }
    }
}
