//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Ma_Lich_Su { get; set; }
        public int Ma_Bai_Hat { get; set; }
        public int Ma_User { get; set; }
        public System.DateTime Ngay_Nghe { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Song Song { get; set; }
    }
}
