//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikedSong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LikedSong()
        {
            this.Songs_Liked = new HashSet<Songs_Liked>();
        }
    
        public int Ma_Yeu_Thich { get; set; }
        public int Ma_User { get; set; }
        public int Ma_Bai_Hat { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Song Song { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Songs_Liked> Songs_Liked { get; set; }
    }
}
