//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs_Liked
    {
        public int ID_Songs_Liked { get; set; }
        public int Ma_Yeu_Thich { get; set; }
        public int Ma_Bai_Hat { get; set; }
    
        public virtual LikedSong LikedSong { get; set; }
        public virtual Song Song { get; set; }
    }
}
